services:
  fastapi-backend:
    build: ./fastapi-server
    container_name: fastapi-backend
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    ports:
      - "8001:8000"
    networks:
      - app-network

  django-backend:
    build: ./django-server
    container_name: django-backend
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    ports:
      - "8002:8000"
    networks:
      - app-network

  node-backend:
    build: ./node-server
    container_name: node-backend
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    ports:
      - "8003:3000"
    networks:
      - app-network

  dotnet-backend:
    build: ./dotnet-server
    container_name: dotnet-backend
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    ports:
      - "8004:8080"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx-lb
    ports:
      - "80:80"
    depends_on:
      - fastapi-backend
      - django-backend
      - node-backend
      - dotnet-backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
